# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see:https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ dev ]
    paths: 
    - 'factorial.py' 
    - 'lint.py' 
    - 'pytest_test.py' 
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint pytest
    - name: Lint with pylint 
      run: |
        python lint.py
    - name: Test with pytest
      run: |
        pytest pytest_test.py
  
  deploy:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials 
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.TEST_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.TEST_AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1 

    - name: Copy files to my S3 bucket
      run: |
        aws s3 cp factorial.py s3://factorial-taupirho
